version = 0.1

[default.deploy.parameters]
stack_name = "acxhange-library-sam"
s3_bucket = "acxhange-library-backend-s3"
s3_prefix = "sam-app"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "ap-south-1"